// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DBModel
{
    public partial class Cities
    {
        public Cities()
        {
            Locations = new HashSet<Locations>();
        }

        public int CityId { get; set; }
        public string Name { get; set; }

        public virtual ICollection<Locations> Locations { get; set; }
    }
}