// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DBModel
{
    public partial class Locations
    {
        public int LocationId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public int CityId { get; set; }
        public decimal Longitude { get; set; }
        public decimal Latitude { get; set; }

        public virtual Cities City { get; set; }
    }
}